-- mysql -u root < schema.sql
create database if not exists ai_scripts;
use ai_scripts;

create table if not exists jobs (
  id            char(36) primary key,   -- uuid4, generated in db.py
  url           text not null,
  json_schema   json not null,
  prompt        text not null,
  status        varchar(16) not null,   -- pending | running | done | failed
  error         text,
  created_at    timestamp default current_timestamp,
  updated_at    timestamp default current_timestamp on update current_timestamp
);

create table if not exists script_attempts (
  id              char(36) primary key,
  job_id          char(36) not null,
  attempt_number  int not null,   -- 0 = replay of a cached script (retry_loop.py),
                                  -- 1..3 = generated by the LLM

  script_code     mediumtext not null,
  error_message   text,           -- null if this attempt succeeded
  output_json     json,           -- null if this attempt failed
  success         boolean not null,
  created_at      timestamp default current_timestamp,
  foreign key (job_id) references jobs(id),
  index script_attempts_job_id_idx (job_id)
);
